development:
  adapter: postgresql
  encoding: unicode
  database: solarsystem_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: solarsystem_test
  pool: 5
  timeout: 5000
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: solarsystem_production
  pool: 5
  timeout: 5000
  password:
